version: "3.3"

services:
  testweb:
    build:
      context: .
      dockerfile: ./Dockerfile-test
    environment:
      PORT: 8080
      JDBC_URL: "jdbc:sqlite:file:test?mode=memory&cache=shared"
    ports:
      - "8080:8080"