version: "3.3"

services:
  featureide:
    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      PORT: 10000
      JDBC_URL: "jdbc:sqlite:file:test?mode=memory&cache=shared"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.featureide.rule=Host(`featureide.localhost`)"
      - "traefik.http.routers.featureide.entrypoints=web"
      - "traefik.http.services.featureide.loadbalancer.server.port=10000"
    networks:
      - vdev

networks:
  vdev:
    external: true