version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
      JDBC_URL: "jdbc:postgresql://db:5432"
      DATABASE: featureide
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: featureide
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
       - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s