FROM gradle:7-jdk19 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
ENV http_proxy "http://127.0.0.1:3001"
ENV https_proxy "http://127.0.0.1:3001"
RUN mkdir lib

ADD https://github.com/FeatureIDE/FeatureIDE/releases/download/v3.9.3/de.ovgu.featureide.lib.fm-v3.9.2.jar lib/de.ovgu.featureide.lib.fm-v3.9.3_new.jar
ADD https://github.com/FeatureIDE/FeatureIDE/raw/v3.9.3/plugins/de.ovgu.featureide.fm.core/lib/antlr-3.4.jar lib/antlr-3.4.jar
ADD https://github.com/FeatureIDE/FeatureIDE/raw/v3.9.3/plugins/de.ovgu.featureide.fm.core/lib/org.sat4j.core.jar lib/org.sat4j.core.jar
ADD https://github.com/FeatureIDE/FeatureIDE/raw/v3.9.3/plugins/de.ovgu.featureide.fm.core/lib/uvl-parser.jar lib/uvl-parser.jar
ADD https://github.com/FeatureIDE/FeatureIDE/raw/v3.9.3/plugins/de.ovgu.featureide.fm.core/lib/SPLCAT.jar lib/SPLCAT.jar
ENTRYPOINT ["gradle","test","--no-daemon"]