# https://www.jetbrains.com/help/idea/run-and-debug-a-spring-boot-application-using-docker-compose.html
services:
  db-test:
    image: postgres
    volumes:
      - ./tmp/db-test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktorjournal
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s