version: "3.3"

services:
  testweb:
    build:
      context: .
      dockerfile: ./Dockerfile-test
    environment:
      PORT: 8080
      JDBC_URL: "jdbc:postgresql://testdb:5432"
      DATABASE: featureide_test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - testdb

  testdb:
    image: postgres
    volumes:
      - ./tmp/testdb:/var/lib/postgresql/testdata
    environment:
      POSTGRES_DB: featureide_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s