version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8080
      JDBC_URL: "jdbc:sqlite:file:test?mode=memory&cache=shared"
    expose:
      - 8080